export const media = {
  brand: {
    logo: "/media/brand/logo-transparent.png",
    logoWhite: "/media/brand/logo-white.png",
    logoOriginal: "/media/brand/logo-original.png",
  },
  hero: {
    background: "/media/hero/hero-team.jpg",
    video: "/media/hero/hero-tech.mp4",
    poster: "/media/hero/tech-abstract.jpg",
    about: "/media/hero/about-office.jpg",
    circuit: "/media/hero/hero-circuit.jpg",
    ai: "/media/hero/hero-ai.jpg",
    websites: "/media/hero/hero-websites.jpg",
    app: "/media/hero/hero-app.jpg",
  },
  nfc: {
    businessCard: "/media/nfc/nfc-business-card.jpg",
    profile: "/media/nfc/nfc-profile.jpg",
    menu: "/media/nfc/nfc-menu.jpg",
    restaurant: "/media/nfc/nfc-restaurant.jpg",
    marketing: "/media/nfc/nfc-marketing.jpg",
    tags: "/media/nfc/nfc-tags.jpg",
    custom: "/media/nfc/nfc-custom.jpg",
  },
  ai: {
    chatbot: "/media/ai/ai-chatbot.jpg",
    support: "/media/ai/ai-support.jpg",
    assistant: "/media/ai/ai-assistant.jpg",
    tools: "/media/ai/ai-tools.jpg",
    integration: "/media/ai/ai-integration.jpg",
  },
  apps: {
    mobileApp: "/media/apps/mobile-app.jpg",
    business: "/media/apps/app-business.jpg",
    customer: "/media/apps/app-customer.jpg",
    interface: "/media/apps/app-interface.jpg",
  },
  websites: {
    build: "/media/websites/website-build.jpg",
    software: "/media/websites/software-build.jpg",
    automation: "/media/websites/automation-build.jpg",
  },
  products: {
    googleReview: "/media/products/nfc-google-review.svg",
    event: "/media/products/nfc-event.svg",
    hotel: "/media/products/nfc-hotel.svg",
    retail: "/media/products/nfc-retail.svg",
    healthcare: "/media/products/nfc-healthcare.svg",
    education: "/media/products/nfc-education.svg",
    dashboard: "/media/products/dashboard.svg",
    adminPanel: "/media/products/admin-panel.svg",
    crm: "/media/products/crm.svg",
  },
} as const;
